---
- name: Copy file with owner and permissions
  hosts: server1 
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: /root/run.sh
        dest: /tmp/run.sh 
        owner: sysadmin 
        group: sysadmin        
        mode: '0555'

    - name: Execute the script
      command: sh /tmp/run.sh
      register: message

    - name: print debug message
      debug:
        msg: "{{ message }}"

