---
- hosts: server1 
  serial: 1
  tasks:
    # task 1
    - name: test connection
      ping:
      register: message

    # task 2
    - name: print debug message
      debug:
        msg: "{{ message }}"

  vars:
      ansible_user: user1
      ansible_pass: xxxxx 
