---
- hosts: server1 
  tasks:
    - name: Check Date with Shell command
      shell:
         "date"
      register: datecmd
      tags: datecmd

    - debug: msg={{ 'server1/database42' | regex_search('database[0-9]+') }}
    - debug: msg={{ 'foo\nBAR' | regex_search('^bar', multiline=True, ignorecase=True) }}
