---
- hosts: server1 
#  gather_facts: no
  vars:
    found: none

  tasks:
    - name: Run rpm 
      shell:
         "rpm -qa"
      register: out

    - debug: 
        msg: found="{{ item }}"
      when: item is regex("fusioninventory-agent")
      loop: "{{ out.stdout_lines  }}"


    - debug: 
        msg: "{{ found }}" 
