---
- name: Copying your php file in the /var/www/html
  copy:
    src: /root/ansibleplaybook/index.php
    dest: /var/www/html/index.php
    force: yes        
  notify: 
      - restart httpd service