---
- hosts: lampstack
  become: yes
  become_method: sudo

  vars_files:
    - vars/default.yml

  tasks:

  - name: Create a new database with name 'myglpi'
    community.mysql.mysql_db:
      name: myglpi 
      state: absent 
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: Create user with password, all database privileges and 'WITH GRANT OPTION' in myglpi 
    community.mysql.mysql_user:
      state: absent 
      name: myglpi 
      priv:
        'myglpi.*': 'ALL,GRANT'
      login_user: root
      login_password: "{{ mysql_root_password }}"

