---
- hosts: all 
  gather_facts: True 
  tasks:

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: user1 
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

