---
- hosts: "{{ variable_host | default('lampstack') }}" 
  become: yes
  become_method: sudo

  vars_files:
    - vars/default.yml

  tasks:
  - name: stop fusioninventory-agent service  
    ansible.builtin.systemd:
      name: fusioninventory-agent
      state: stopped

  - name: stop fusioninventory-agent service
    ansible.builtin.systemd:
      name: fusioninventory-agent
      enabled: no 


